---
name: Checks

on: [ push ]


jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          mkdir app/app/env
          echo "Success make env directory"
          touch app/app/env/secret_env.py
          echo "Success make env file"
          echo ${DJANGO_ENV} >> app/app/env/secret_env.py
          echo "Success writing env data"
        env:
          DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"