---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: CI env test
        env:
          TEST_ENV_VARIABLE: test-env-variable-123456789
        run: echo ${TEST_ENV_VARIABLE}
      - name: Create env file
        run: |
          pwd
          touch app/.env/.env.json
          echo ${{ secrets.DJANGO_ENV}} >> app/.env/env.json
          tail -1 app/.env/.env.json
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"